In [1]:
# first import numpy so import numpy library which is already downloaded
import numpy as np


In [2]:
#------------------------ARRAY CREATION USING LIST-------------------#
# while creating an array in numpy it is created using a list 
arr1  = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
# ----------------------DIFFERENCE BTW ARRAY LIST OUTPUT----------------------------#
arr2 = [1,2,3,4,5]
arr2

[1, 2, 3, 4, 5]

In [4]:
# -------------------------USE OF MULTIPLE DATATYPES--------------------#

lst = [1,2,"hello"]
print(lst)
arr = np.array(lst)
print(arr)
# U21 datatype that means all the datatypes have been changed to unicodes.. i.e converted to strings..
# as array elements must have single datatype 1 and 2 are changed to strings to match with hello

lst1 = [1,2,5.6]
print(lst1)
arr1 = np.array(lst1)
print(arr1)

[1, 2, 'hello']
['1' '2' 'hello']
[1, 2, 5.6]
[1.  2.  5.6]


In [5]:
#------------------------ARRAY , LIST ONE AND TWO DIMENSIONS-------------------#

# To create a matrix we will do list inside of lists and print it , it will be in single line as one dimension
l = [ [1,2,3] , [4,5,6] ,[7,8,9] ]
print(l)

arr = np.array(l)
print(arr)

# also 3D , 4D do exist as well which are in Tensorflow library in python

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
