In [5]:
import numpy as np
import random

In [22]:
#-----------------------ATTRIBUTES---------------------#

# While calling attributes we dont use () brakcets at the end arr.shape not arr.shape() 
# as brakcet is used while calling a method

arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr)

print(arr.shape)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [19]:
#----------------------METHODS-------------------------------#

arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print(arr)

print(arr.min())
print(arr.max())
print(arr.sum())

# To calculate sum of specific rows and columns
# np.sum(arr,axis=0) np.sum(arr,axis=1) 
# --> axis = 0 is vertical i.e column wise sum 
# --> axis = 1 is horzontal i.e row wise sum
arr_cols = np.sum(arr,axis=0)
print(arr_cols)

arr_rows = np.sum(arr ,axis=1)
print(arr_rows)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
45
[12 15 18]
[ 6 15 24]


In [28]:
#--------------MEAN : STD DEVIATION : ARGMAX : ARGMIN--------------#

arr = np.array( [ [1,2,3] ,[4,5,6] , [7,8,9] ])
print(arr)

mean = arr.mean()
mean_row = np.mean(arr , axis=1)
mean_col = np.mean(arr , axis=0)

print( mean ,  mean_row , mean_col)

index_max_element = arr.argmax()
index_min_element = arr.argmin()
print(f"index : {index_max_element} , {index_min_element} ")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0 [2. 5. 8.] [4. 5. 6.]
index : 8 , 0 
