In [1]:
import numpy as np

In [3]:
#-----------------------GENERATE 1D ARRAY--------------#

arr = np.arange(1,11) # to create array of 1 to N-1 just like for loops 
print(arr)
arr1 = np.zeros(6) 
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[0. 0. 0. 0. 0. 0.]


In [10]:
#--------------------GENERATE 2D ARRAY OR MATRICES----------------------------#
arr = np.zeros((3,3))
print(arr)

arr1 = np.ones((2,3))
print(arr1)

arr2 = np.zeros((6,10))
print(arr2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
#-----------------------LINSPACE FUNCTION---------------------#

# press shift tab to see what any function does..
# np.linspace(start, end , no. of evenly spaced numbers we want)  ---> returns evenly spaced numbers over a specified interval

arr = np.linspace(1,5,2)
print(arr)

arr = np.linspace(1,5,3)
print(arr)

arr = np.linspace(1,5,5)
print(arr)

arr = np.linspace(1,5,10)
print(arr)



[1. 5.]
[1. 3. 5.]
[1. 2. 3. 4. 5.]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
