In [3]:
import numpy as np

In [4]:
#-------------ARITHMETIC OPEARTIONS-----------#

a1 = np.arange(1,6)
a2 = np.arange(6,11)
print( a1 , a2 )

[1 2 3 4 5] [ 6  7  8  9 10]


In [5]:
# while adding,subtracting size must be same , common usecase in pandas in any dataframe null values must be filled by something 
# so opearations can be performed

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1//a2) # a1//a2 is floor divison , integer part of output is considered
print(a1**a2) # a1**a2 means power function (element of a1) to the power (element of a2)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[      1     128    6561  262144 9765625]


In [11]:
#-------------ON 2D MATRICES-------------#
arr1 = np.arange(1,26).reshape(5,5)
print(arr1)

print(arr1+10)
print(arr1*2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
