In [10]:
import numpy as np 

In [12]:
# Broadcasting is we can't do 
l = [1,2,3,4]
print(l+10) # this will give me error but numpy arrays can be broadcasted 



TypeError: can only concatenate list (not "int") to list

In [16]:
arr1 = np.arange(1,11)
print(arr1)

print(arr1+10)
print(arr1*2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
