In [4]:
import numpy as np

In [5]:
#---------------BOOLEAN INDEXING-------------3

#  TO GET EVEN NUMBERS FROM ARRAY WE CANT SLICE IT 

arr = np.arange(1,11)
print(arr)

bool_index = arr%2==0
print(bool_index)
print(arr[bool_index])


[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [7]:
# TO GET ODD NUMBERS

print(arr)
bool_index = arr%2 !=0
print(bool_index)
print(arr[bool_index])


[ 1  2  3  4  5  6  7  8  9 10]
[ True False  True False  True False  True False  True False]
[1 3 5 7 9]
