In [1]:
import numpy as np

In [2]:
# --------------------FIND IF SUDOKU VALID ---------------------#

sudoku = np.array([
    
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
# -------------------------SUM OF EVERY ROWS AND COLUMNS-----------------------#


print(np.sum(sudoku))
print("\nSUM OF ROWS")
rows_sum = np.sum(sudoku ,axis =1)
print(rows_sum)
print(rows_sum == 45)

print("\nSUM OF COLUMNS")
cols_sum = np.sum(sudoku , axis =0)
print(cols_sum)
print(cols_sum ==45)

for i in rows_sum :
    if i!=45:
        print("\nSudoku is not valid ")
        break
else :
    print("\nSudoku is valid Row wise")
for i in cols_sum: 
    if i!=45:
        print("\nSudoku is not valid ")
        break
else :
    print("\nSudoku is valid Column wise")


405

SUM OF ROWS
[45 45 45 45 45 45 45 45 45]
[ True  True  True  True  True  True  True  True  True]

SUM OF COLUMNS
[45 45 45 45 45 45 45 45 45]
[ True  True  True  True  True  True  True  True  True]

Sudoku is valid Row wise

Sudoku is valid Column wise


In [4]:
# -----------------SUM OF 3 * 3 MATRICES METHOD 1------------------# 

col_split = np.hsplit(sudoku , 3)
for item in col_split:
    print("Matrix : \n" , item)
    print("\n")



Matrix : 
 [[5 3 4]
 [6 7 2]
 [1 9 8]
 [8 5 9]
 [4 2 6]
 [7 1 3]
 [9 6 1]
 [2 8 7]
 [3 4 5]]


Matrix : 
 [[6 7 8]
 [1 9 5]
 [3 4 2]
 [7 6 1]
 [8 5 3]
 [9 2 4]
 [5 3 7]
 [4 1 9]
 [2 8 6]]


Matrix : 
 [[9 1 2]
 [3 4 8]
 [5 6 7]
 [4 2 3]
 [7 9 1]
 [8 5 6]
 [2 8 4]
 [6 3 5]
 [1 7 9]]




In [5]:
for item in col_split:
    row_split = np.vsplit(item,3)
    for item1 in row_split:
            
        print("Matrix:  \n" , item1)
        sum = np.sum(item1)
        print("Sum: ",sum)

        if sum != 45:
            print(" Sudoku iS not valid for 3 * 3 individual boxes")
        
        print("\n")
    

Matrix:  
 [[5 3 4]
 [6 7 2]
 [1 9 8]]
Sum:  45


Matrix:  
 [[8 5 9]
 [4 2 6]
 [7 1 3]]
Sum:  45


Matrix:  
 [[9 6 1]
 [2 8 7]
 [3 4 5]]
Sum:  45


Matrix:  
 [[6 7 8]
 [1 9 5]
 [3 4 2]]
Sum:  45


Matrix:  
 [[7 6 1]
 [8 5 3]
 [9 2 4]]
Sum:  45


Matrix:  
 [[5 3 7]
 [4 1 9]
 [2 8 6]]
Sum:  45


Matrix:  
 [[9 1 2]
 [3 4 8]
 [5 6 7]]
Sum:  45


Matrix:  
 [[4 2 3]
 [7 9 1]
 [8 5 6]]
Sum:  45


Matrix:  
 [[2 8 4]
 [6 3 5]
 [1 7 9]]
Sum:  45




In [6]:
# -------------- SUM OF 3*3 MATRICES METHOD 2-----------------#

for i in range(0,9,3):
    for j in range(0,9,3):
        matrix = sudoku[i:i+3,j:j+3]
        print("Matrix : \n", matrix)
        print("Sum: ", matrix.sum())

        box_sum = np.sum(matrix)
        if(sum!=45):
            print(" Sudoku iS not valid for 3 * 3 individual boxes")
        
        print("\n")


Matrix : 
 [[5 3 4]
 [6 7 2]
 [1 9 8]]
Sum:  45


Matrix : 
 [[6 7 8]
 [1 9 5]
 [3 4 2]]
Sum:  45


Matrix : 
 [[9 1 2]
 [3 4 8]
 [5 6 7]]
Sum:  45


Matrix : 
 [[8 5 9]
 [4 2 6]
 [7 1 3]]
Sum:  45


Matrix : 
 [[7 6 1]
 [8 5 3]
 [9 2 4]]
Sum:  45


Matrix : 
 [[4 2 3]
 [7 9 1]
 [8 5 6]]
Sum:  45


Matrix : 
 [[9 6 1]
 [2 8 7]
 [3 4 5]]
Sum:  45


Matrix : 
 [[5 3 7]
 [4 1 9]
 [2 8 6]]
Sum:  45


Matrix : 
 [[2 8 4]
 [6 3 5]
 [1 7 9]]
Sum:  45


